on: push
name: 🚀 Deploy staging on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.carbar.ch
        username: carbar_tailwind
        password: ${{ secrets.FTP_TAILWIND_SECRET }}
